### ISSUE TITLE
getDynamicPageUrl results in error

### ISSUE THREAD

**Issue by StefanRetief** [agility/agility-next#3]
When attempting to preview a post I've made on agility CMS, I get a 404 followed by a 500 internal server error.

I am using the agility-nextjs-blog starter, and haven't modified the ```/api/preview```, except for changing it to a ts file. It looks like the following:

```typescript
export default async (req, res) => {

	//validate our preview key, also validate the requested page to preview exists
	const validationResp = await validatePreview({
		agilityPreviewKey: req.query.agilitypreviewkey,
		slug: req.query.slug
	});

	if (validationResp.error) {
		return res.status(401).end(`${validationResp.message}`)
	}

	let previewUrl = req.query.slug;

	//TODO: these kinds of dynamic links should work by default (even outside of preview)
	if(req.query.ContentID) {
		const dynamicPath = await getDynamicPageURL({contentID: req.query.ContentID, preview: true, slug: req.query.slug});
		if(dynamicPath) {
			previewUrl = dynamicPath;
		}
	}

	//enable preview mode
	res.setPreviewData({})

	// Redirect to the slug
	res.writeHead(307, { Location: previewUrl })
	res.end()

}
```

The error I get when using this api is the following: 

```
TypeError: agilityRestClient.getSitemap is not a function
    at D:\Projects\test\node_modules\@agility\nextjs\node.js:446:60
    at step (D:\Projects\test\node_modules\@agility\nextjs\node.js:33:23)
    at Object.next (D:\Projects\test\node_modules\@agility\nextjs\node.js:14:53)
    at D:\Projects\test\node_modules\@agility\nextjs\node.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Projects\test\node_modules\@agility\nextjs\node.js:4:12)
    at getDynamicPageURL (D:\Projects\test\node_modules\@agility\nextjs\node.js:433:12)
    at exports.modules../pages/api/preview.tsx.__webpack_exports__.default (D:\Projects\test\.next\server\pages\api\preview.js:35:102)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async apiResolver (D:\Projects\test\node_modules\next\dist\next-server\server\api-utils.js:8:1)
```

**PACKAGE.JSON**:
```json
"dependencies": {
    "next": "^11.0.1",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-html-parser": "^2.0.2",
    "react-icons": "^4.2.0"
  },
  "devDependencies": {
    "@agility/content-fetch": "^1.1.1",
    "@agility/content-sync": "^1.0.3",
    "@agility/nextjs": "^0.2.0",
    "@tailwindcss/typography": "^0.4.1",
    "@types/node": "^14.14.35",
    "@types/react": "^17.0.3",
    "autoprefixer": "^10.2.5",
    "cross-env": "^7.0.3",
    "postcss": "^8.2.8",
    "tailwindcss": "^2.2.4",
    "truncate-html": "^1.0.3",
    "typescript": "^4.2.3"
  }
```

**REPRO**:

0. Head to agility CMS
1. Start by creating new content and filling the appropriate fields.
2. Once the fields are filled, hit the preview button.
3. Follow the new window that is produced and notice that the website will return a 404 followed by a 500.

**Comment by joelvarty** [comment]
I've been having similar issues with Preview Mode on Netlify.  We'll continue to investigate - we may need to get their team involved.

**Comment by joshua-isaac** [comment]
Hi @StefanRetief, this should be fixed by updating the `@agility/next` package in your starter to the latest version `0.2.1`.

When previewing a Dynamic Page Item from the CMS, it should now 404, then redirect to the item. Still not the best experience, but we are working to improve this! :)

**Comment by jamesvidler** [comment]
@StefanRetief are you still experiencing issues here after @joshua-isaac recommendation?
